@startuml
class org.example.app.repository.impl.ContactRepositoryImpl {
- {static} String TABLE_CONTACTS
+ String create(Contact)
+ Optional<List<Contact>> read()
+ String update(Contact)
+ String delete(Long)
+ Optional<Contact> readById(Long)
- boolean isIdExists(Long)
}


class org.example.app.service.ContactService {
~ ContactRepositoryImpl repository
+ String create(Map<String,String>)
+ String read()
+ String update(Map<String,String>)
+ String delete(Map<String,String>)
+ String readById(Map<String,String>)
}


class org.example.app.view.ContactReadByIdView {
+ Map<String,String> getData()
+ void getOutput(String)
}

class org.example.app.controller.ContactController {
~ ContactService service
+ void create()
+ void read()
+ void update()
+ void delete()
+ void readById()
}


class org.example.app.service.AppService {
~ ContactController controller
+ void handleOption(int)
}


class org.example.app.view.ContactReadView {
+ void getOutput(String)
}

class org.example.app.utils.AppStarter {
+ {static} void startApp()
}

class org.example.app.utils.Constants {
+ {static} String WRONG_PHONE_MSG
+ {static} String WRONG_EMAIL_MSG
+ {static} String WRONG_ID_MSG
+ {static} String DATA_ABSENT_MSG
+ {static} String DATA_INSERT_MSG
+ {static} String DATA_UPDATE_MSG
+ {static} String DATA_DELETE_MSG
+ {static} String APP_CLOSE_MSG
+ {static} String INPUT_REQ_MSG
+ {static} String INCORRECT_VALUE_MSG
+ {static} String INCORRECT_OPTION_MSG
}

class org.example.app.entity.Contact {
- Long id
- String firstName
- String lastName
- String phone
- String email
+ Long getId()
+ void setId(Long)
+ String getFirstName()
+ void setFirstName(String)
+ String getLastName()
+ void setLastName(String)
+ String getPhone()
+ void setPhone(String)
+ String getEmail()
+ void setEmail(String)
+ String toString()
}


class org.example.app.config.DBConn {
+ {static} Connection connect()
}

class org.example.app.utils.ContactValidator {
+ Map<String,String> validateContactData(Map<String,String>)
}

class org.example.app.controller.AppController {
~ AppView view
~ AppService service
+ void runApp()
}


class org.example.app.view.ContactCreateView {
+ Map<String,String> getData()
+ void getOutput(String)
}

class org.example.app.mapper.ContactMapper {
+ Contact mapData(Map<String,String>)
}

class org.example.app.exceptions.ContactException {
~ Map<String,String> errors
+ String getErrors(Map<String,String>)
}


class org.example.app.view.ContactUpdateView {
+ Map<String,String> getData()
+ void getOutput(String)
}

class org.example.app.view.AppView {
+ int getOption()
- void getMenu()
+ void getOutput(String)
}

class org.example.app.exceptions.OptionException {
}
class org.example.app.App {
+ {static} void main(String[])
}

class org.example.app.view.ContactDeleteView {
+ Map<String,String> getData()
+ void getOutput(String)
}

class org.example.app.utils.AppValidator {
+ {static} String ID_RGX
+ {static} String PHONE_RGX
+ {static} String EMAIL_RGX
+ {static} boolean isIdValid(String)
+ {static} boolean isPhoneValid(String)
+ {static} boolean isEmailValid(String)
}


interface org.example.app.repository.ContactRepository {
~ String create(T)
~ Optional<List<T>> read()
~ String update(T)
~ String delete(Long)
~ Optional<T> readById(Long)
}



org.example.app.repository.ContactRepository <|.. org.example.app.repository.impl.ContactRepositoryImpl
org.example.app.exceptions.RuntimeException <|-- org.example.app.exceptions.ContactException
org.example.app.exceptions.Exception <|-- org.example.app.exceptions.OptionException
@enduml